version: '3.8'
services:
  db:
    image: redis:7.2.3-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./data:/data
    env_file:
      - .env

  api:
    hostname: api
    build: ./api
    restart: unless-stopped


  round-mover:
    hostname: round-mover
    build: .
    restart: unless-stopped
    command: yarn run manage testnet
    env_file:
      - .env
    depends_on:
      - db


  events-listener:
    hostname: events-listener
    build: .
    restart: unless-stopped
    command: yarn run eventsListener testnet
    env_file:
      - .env
    depends_on:
      - db



